source 'https://github.com/jghg02/JCore-ui.git'

use_frameworks!

target 'JCore-ui_Example' do
  pod 'JCore-ui', :path => '../'

  target 'JCore-ui_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
